name: Run sp-p3.py

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: 每日签到，参数13，使用“ python sp-p3.py 13”运行
      env:
        NAME: ${{ secrets.SELF_NAME }}
        PASSWORD: ${{ secrets.SELF_PASSWORD }}
      run: python sp-p3.py 13
      
    - name: 每周签到，参数14，使用“ python sp-p3.py 14”运行
      env:
        NAME: ${{ secrets.SELF_NAME }}
        PASSWORD: ${{ secrets.SELF_PASSWORD }}
      run: python sp-p3.py 14
